name: Push Sitemap Parser Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:

# Push image to Docker Hub.
    push-js-to-docker:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'

        steps:
            - uses: actions/checkout@v2

            - name: Prepare
              id: prep
              run: |
                  VERSION=edge
                  if [[ $GITHUB_REF == refs/tags/* ]]; then
                  VERSION=${GITHUB_REF#refs/tags/}
                  else VERSION=latest
                  fi
                  echo ::set-output name=version::${VERSION}

            -
              name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            -
              name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            -
              name: Build and push sitemap parser image
              id: docker_build_parser
              uses: docker/build-push-action@v2
              with:
                file: sitemap-parser/Dockerfile
                push: true
                tags: smclab/openk9-sitemap-parser:${{ steps.prep.outputs.version }}